config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'signup' => 'users#new', as: :new_user
  post 'signup' => 'users#create', as: :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  # resources :posts, only:[:index,:new,:create]


  #nested routes
  resources :posts do
    resources :votes, :only =>[:create]
    resources :comments
  end


  resources :users, :only => [:show] do
    resources :votes, :only =>[:create]
  end


end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
require 'uri'

class Post < ActiveRecord::Base

  validates :link,
  presence: true,
  format: {:with => URI::regexp(%w(http https))}

  validates :title,
  presence: true

  belongs_to :user
  has_many :votes, as: :votable

  has_many :comments

  def owned_by? user
    user && user.id == self.user.id
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  #minimal email validation
  #because I agree with this: http://davidcel.is/posts/stop-validating-email-addresses-with-regex/
  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: {with: /@/}

  has_many :comments

  #posts I created
  has_many :posts

  #votes I created
  has_many :ratings, class_name: 'Vote'

  #votes about me
  has_many :votes, as: :votable

  def display_name
    self.name || 'Anon'
  end

  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def check_auth
    unless current_user
      flash[:warning] = "You must be logged in to access that page."
      redirect_to login_path
    end
  end

  def check_no_auth
    redirect_to root_path if current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def load_model
    return unless params[:id]
    model_name = params[:controller].singularize
    my_model = model_name.classify.safe_constantize
    model_inst = my_model.find params[:id]
    instance_variable_set("@#{model_name}",model_inst)
  end

  def check_ownership
    model_name = params[:controller].singularize
    model_inst = instance_variable_get("@#{model_name}")
    owner = model_inst.user
    if owner.nil? || owner.id != current_user.id
      flash[:danger] = "You cannot change that which does not belong to you."
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end


  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @current_user
    @comment = @post.comments.create(comment_params)
    @current_user.comments << @comment
    redirect_to post_comments_path(@post)
  end






  private
  def comment_params
    params.require(:comment).permit(:body)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :check_auth, except: [:index]
  before_action :load_model, only:[:edit,:update,:destroy]
  before_action :check_ownership, only: [:edit,:update,:destroy]

  def index
    @posts = Post.all
    respond_to do |format|
      format.html
      format.json {render json: @posts}
      format.xml {render xml: @posts}
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create post_params
    if @post.persisted?
      flash[:success] = "Your link has been posted."
      redirect_to root_path
    else
      flash[:danger] = @post.errors.full_messages.uniq.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    @post.update post_params
    if @post.save
      flash[:success] = "Your link has been updated."
      redirect_to root_path
    else
      flash[:danger] = @post.errors.full_messages.uniq.to_sentence
      render :edit
    end

  end

  def destroy
    @post.delete
    render json:{}
  end

  private

  def post_params
    params.require(:post).permit(:title,:link)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :check_no_auth, except: [:destroy]

  def new
  end

  def create
    user = User.authenticate(params[:user][:email], params[:user][:password])
    if(user)
      session[:user_id] = user.id
      flash[:success] = "You are logged in."
      redirect_to root_path
    else
      flash[:danger] = "Invalid email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "You are logged out."
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_no_auth

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.persisted?
      flash[:success] = "You are signed up. Login below."
      redirect_to login_path
    else
      flash[:danger] = @user.errors.full_messages.uniq.to_sentence
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,:name,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Comment</h3>
    </div>
    <div class="panel-body">
      <%= bootstrap_form_for [:post, @comment] do |f| %>
      <%= f.text_area :body, placeholder: 'Comment Content' %>
      <%= f.primary "Post Comments" %>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Teh H4x0r N3ws</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "New Post", new_post_path %></a></li>
        <li><%= link_to "About", "#" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.display_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Profile</a></li>
              <li><a href="#">Settings</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out",logout_path %></a></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/signup">Sign Up</a></li>
          <li><a href="/login">Log In</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hax0rn3ws</title>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/nav' %>
<div class="container">
  <div class="row">
    <%= render partial: 'shared/flash' %>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= bootstrap_form_for @post do |f| %>
  <%= f.text_field :title, placeholder: 'My interesting title' %>
  <%= f.text_field :link, placeholder: 'http://www.example.com' %>
  <%= f.primary "Post" %>
<% end %>

app/views/posts/edit.html.erb
<div class="col-sm-offset-4 col-sm-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Edit post</h3>
    </div>
    <div class="panel-body">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="col-sm-8">
  <table class="table table-striped">
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
          <%= bootstrap_form_for [post,Vote.new] do |f| %>
              <%= f.button "", value: 'up', class: 'btn btn-primary btn-xs glyphicon glyphicon-chevron-up' %><br>
              <%= f.button "", value: 'down', class: 'btn btn-primary btn-xs glyphicon glyphicon-chevron-down' %>
            <% end %>
          </td>
          <td> <%= post.votes.reduce(0){ |sum,v| sum + v.value} %>
            <a href="<%= post.link %>"><%= post.title %></a>
          </td>
          <td><%= post.user.display_name %></td>
          <td><%= format_creation_time post %></td>
          <td>0 Comments</td>
          <td>
          <%= link_to "", new_post_comment_path(post), class: 'glyphicon glyphicon-comment' %>
          <!--% if @current_user && @current_user.id == post.user.id %-->
          <% if post.owned_by? @current_user %>
            <%= link_to "", edit_post_path(post), class: 'glyphicon glyphicon-pencil' %>
            <%= link_to "", post, data:{confirm: 'Are you sure?'}, class: 'js-delete glyphicon glyphicon-trash' %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="col-sm-4">
  <div class="advertisement">
    <div class="text">
      THIS IS AN<br>
      ADVERTISEMENT
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= bootstrap_form_for @post do |f| %>
<%= f.text_field :title %>
<%= f.text_area :link %>
<%= f.primary %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %> <!-- k - key v- value -->
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Sign Up</h3>
    </div>
    <div class="panel-body">
      <%= bootstrap_form_for @user do |f| %>
        <%= f.text_field :email %>
        <%= f.text_field :name %>
        <%= f.password_field :password %>
        <%= f.primary "Join Now" %>
      <% end %>
    </div>
  </div>
</div>